version: '3'
services:
  db:
    image: jhenck57/arc_gis:mariadb
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - webnet
      - proxy
    restart_policy:
        condition: always

  drupal:
    depends_on:
      - db
    image: jhenck57/arc_gis:drupal
    ports:
      - "7200:80"
    networks:
      - webnet
      - proxy
    volumes:
      - ./app:/app
    restart: 
      restart_condition: always

  jupyter:
    image: jhenck57/arc_gis:jupyter_gis
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.5"
          memory: 9200M
      restart_policy:
        condition: on-failure
    ports:
      - "8888:8888"
      - "8889:8889"
    networks:
      - webnet
      - proxy
  
networks:
  default:
    external: false
  proxy:
    external: true

volumes:
  db_data:
  app:

